import { CalendarClock, FileText, SquareCheckBig, Users } from "lucide-react";
import { isoFromToday } from "./demoEvents";
import type {
  PreviewDeadline,
  PreviewNotification,
  PreviewPriority,
  PreviewRisk,
  PreviewStat,
} from "@/types";

/* =========================================================================
   TEMPORARY PREVIEW DATA — dashboard layout only.
   Numbers are illustrative sample content, not backend values.
   ========================================================================= */

export const DEMO_STATS: PreviewStat[] = [
  {
    id: "open-tasks",
    label: "Open tasks",
    value: "34",
    hint: "9 due within 7 days",
    icon: SquareCheckBig,
    tone: "brand",
    trend: { direction: "down", label: "-6 this week", tone: "success" },
  },
  {
    id: "volunteers",
    label: "Volunteers confirmed",
    value: "112",
    hint: "of 140 roster slots",
    icon: Users,
    tone: "info",
    trend: { direction: "up", label: "+18 this week", tone: "success" },
  },
  {
    id: "documents",
    label: "Documents pending",
    value: "6",
    hint: "2 permits awaiting signature",
    icon: FileText,
    tone: "warning",
    trend: { direction: "flat", label: "No change", tone: "neutral" },
  },
  {
    id: "readiness",
    label: "Event readiness",
    value: "68%",
    hint: "Target 85% by next Friday",
    icon: CalendarClock,
    tone: "success",
    trend: { direction: "up", label: "+7 pts", tone: "success" },
  },
];

export const DEMO_DEADLINES: PreviewDeadline[] = [
  {
    id: "d1",
    title: "Submit venue safety certificate",
    module: "Documents",
    owner: "Priya N.",
    dueIso: isoFromToday(1),
    status: "at-risk",
  },
  {
    id: "d2",
    title: "Confirm keynote AV requirements",
    module: "Tasks",
    owner: "Marcus L.",
    dueIso: isoFromToday(3),
    status: "active",
  },
  {
    id: "d3",
    title: "Close volunteer shift sign-up",
    module: "Volunteers",
    owner: "Rina K.",
    dueIso: isoFromToday(6),
    status: "planned",
  },
  {
    id: "d4",
    title: "Publish attendee run sheet",
    module: "Announcements",
    owner: "Tomás B.",
    dueIso: isoFromToday(11),
    status: "planned",
  },
];

export const DEMO_PRIORITIES: PreviewPriority[] = [
  {
    id: "p1",
    title: "Approve catering contract revision",
    context: "Blocking the finance sign-off",
    owner: "Rina K.",
    priority: "high",
  },
  {
    id: "p2",
    title: "Review 12 new volunteer applications",
    context: "Registration desk still short 8 people",
    owner: "Priya N.",
    priority: "high",
  },
  {
    id: "p3",
    title: "Send committee meeting agenda",
    context: "Meeting scheduled for tomorrow 18:00",
    owner: "Marcus L.",
    priority: "medium",
  },
  {
    id: "p4",
    title: "Update sponsor logo pack",
    context: "Two sponsors upgraded tier",
    owner: "Tomás B.",
    priority: "low",
  },
];

export const DEMO_RISKS: PreviewRisk[] = [
  {
    id: "r1",
    title: "Registration desk understaffed on day 1",
    area: "Volunteers",
    severity: "high",
    mitigation: "Reassign 4 floaters from the expo team",
  },
  {
    id: "r2",
    title: "Outdoor stage weather exposure",
    area: "Operations",
    severity: "medium",
    mitigation: "Hold covered hall as contingency until day −3",
  },
  {
    id: "r3",
    title: "Sponsor branding delivery late",
    area: "Partnerships",
    severity: "low",
    mitigation: "Print buffer booked with local supplier",
  },
];

/** Placeholder copy for the future AI briefing — not generated by a model. */
export const DEMO_BRIEFING_POINTS: string[] = [
  "Volunteer coverage improved to 80% — registration and expo desks remain the two gaps.",
  "Two documents block the finance sign-off; both sit with the venue liaison.",
  "Readiness is trending on target, but day-1 staffing is the dominant risk.",
];

export const DEMO_NOTIFICATIONS: PreviewNotification[] = [
  {
    id: "n1",
    title: "Safety certificate due tomorrow",
    body: "Documents · TechFest 2026",
    timeLabel: "12m ago",
    tone: "warning",
  },
  {
    id: "n2",
    title: "8 volunteers joined the roster",
    body: "Volunteers · TechFest 2026",
    timeLabel: "2h ago",
    tone: "success",
  },
  {
    id: "n3",
    title: "Committee meeting moved to 18:00",
    body: "Meetings · TechFest 2026",
    timeLabel: "Yesterday",
    tone: "info",
  },
];
